/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package p7;

import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import sm.amc.iu.Lienzo2D;
import sm.amc.iu.Lienzo2D.Forma;

import java.awt.Color;
import java.awt.Stroke;
import java.io.File;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;


/**
 * Clase Ventana Principal
 * 
 * @author aidam
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Constructor de la clase
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(1280, 720);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        ButtonLinea = new javax.swing.JToggleButton();
        ButtonRectang = new javax.swing.JToggleButton();
        ButtonCirc = new javax.swing.JToggleButton();
        ButtonFantasma = new javax.swing.JToggleButton();
        ButtonSeleccion = new javax.swing.JToggleButton();
        ButtonColor = new javax.swing.JButton();
        ButtonRellenar = new javax.swing.JToggleButton();
        ButtonTransparencia = new javax.swing.JToggleButton();
        ButtonAlisado = new javax.swing.JToggleButton();
        SliderGrosor = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BarraDeEstado = new javax.swing.JLabel();
        lienzo = new sm.amc.iu.Lienzo2D();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        ButtonLinea.setIcon(new javax.swing.ImageIcon("C:\\Users\\aidam\\Desktop\\AIDA\\6Curso\\2Cuatri\\SMM\\iconos\\linea.png")); // NOI18N
        ButtonLinea.setSelected(true);
        ButtonLinea.setFocusable(false);
        ButtonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLineaActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonLinea);

        ButtonRectang.setIcon(new javax.swing.ImageIcon("C:\\Users\\aidam\\Desktop\\AIDA\\6Curso\\2Cuatri\\SMM\\iconos\\rectangulo.png")); // NOI18N
        ButtonRectang.setFocusable(false);
        ButtonRectang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonRectang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonRectang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRectangActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonRectang);

        ButtonCirc.setIcon(new javax.swing.ImageIcon("C:\\Users\\aidam\\Desktop\\AIDA\\6Curso\\2Cuatri\\SMM\\iconos\\elipse.png")); // NOI18N
        ButtonCirc.setFocusable(false);
        ButtonCirc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonCirc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonCirc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCircActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonCirc);

        ButtonFantasma.setIcon(new javax.swing.ImageIcon("C:\\Users\\aidam\\Desktop\\AIDA\\6Curso\\2Cuatri\\SMM\\Iconos-20240416\\fantasma.png")); // NOI18N
        ButtonFantasma.setFocusable(false);
        ButtonFantasma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonFantasma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonFantasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFantasmaActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonFantasma);

        ButtonSeleccion.setIcon(new javax.swing.ImageIcon("C:\\Users\\aidam\\Desktop\\AIDA\\6Curso\\2Cuatri\\SMM\\Iconos-20240416\\seleccion.png")); // NOI18N
        ButtonSeleccion.setFocusable(false);
        ButtonSeleccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonSeleccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSeleccionActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonSeleccion);

        ButtonColor.setBackground(new java.awt.Color(0, 0, 0));
        ButtonColor.setFocusable(false);
        ButtonColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonColor.setMaximumSize(new java.awt.Dimension(34, 32));
        ButtonColor.setMinimumSize(new java.awt.Dimension(34, 32));
        ButtonColor.setPreferredSize(new java.awt.Dimension(34, 32));
        ButtonColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonColorActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonColor);

        ButtonRellenar.setIcon(new javax.swing.ImageIcon("C:\\Users\\aidam\\Desktop\\AIDA\\6Curso\\2Cuatri\\SMM\\Iconos-20240416\\rellenar.png")); // NOI18N
        ButtonRellenar.setFocusable(false);
        ButtonRellenar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonRellenar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonRellenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRellenarActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonRellenar);

        ButtonTransparencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\aidam\\Desktop\\AIDA\\6Curso\\2Cuatri\\SMM\\Iconos-20240416\\transparencia.png")); // NOI18N
        ButtonTransparencia.setFocusable(false);
        ButtonTransparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonTransparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonTransparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransparenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonTransparencia);

        ButtonAlisado.setIcon(new javax.swing.ImageIcon("C:\\Users\\aidam\\Desktop\\AIDA\\6Curso\\2Cuatri\\SMM\\Iconos-20240416\\alisar.png")); // NOI18N
        ButtonAlisado.setFocusable(false);
        ButtonAlisado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAlisado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonAlisado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlisadoActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonAlisado);

        SliderGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderGrosorStateChanged(evt);
            }
        });
        jToolBar1.add(SliderGrosor);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(90, 22));
        jPanel3.setLayout(new java.awt.BorderLayout());

        BarraDeEstado.setText("Barra de estado");
        jPanel3.add(BarraDeEstado, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        jMenuArchivo.setText("Archivo");

        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemNuevo);

        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAbrir);

        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardar);

        jMenuBar1.add(jMenuArchivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLineaActionPerformed
        // TODO add your handling code here:
        //this.lienzo.setTipoForma(0);
        this.lienzo.setTipoForma(Forma.LINEA);
        this.ButtonRectang.setSelected(false);
        this.ButtonCirc.setSelected(false);
        this.ButtonFantasma.setSelected(false);
        this.ButtonSeleccion.setSelected(false);
        this.lienzo.setMover(false);
        
    }//GEN-LAST:event_ButtonLineaActionPerformed

    private void ButtonRectangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRectangActionPerformed
        // TODO add your handling code here:
        //this.lienzo.setTipoForma(1);
        this.lienzo.setTipoForma(Forma.RECTANGULO);
        this.ButtonLinea.setSelected(false);
        this.ButtonCirc.setSelected(false);
        this.ButtonFantasma.setSelected(false);
        this.ButtonSeleccion.setSelected(false);
        this.lienzo.setMover(false);
    }//GEN-LAST:event_ButtonRectangActionPerformed

    private void ButtonCircActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCircActionPerformed
        // TODO add your handling code here:
        //this.lienzo.setTipoForma(2);
        this.lienzo.setTipoForma(Forma.ELIPSE);
        this.ButtonLinea.setSelected(false);
        this.ButtonRectang.setSelected(false);
        this.ButtonFantasma.setSelected(false);
        this.ButtonSeleccion.setSelected(false);
        this.lienzo.setMover(false);
    }//GEN-LAST:event_ButtonCircActionPerformed

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser dig = new JFileChooser();
        int resp = dig.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION){
            File f = dig.getSelectedFile();
        }
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        // TODO add your handling code here:        
        JFileChooser dig = new JFileChooser();
        int resp = dig.showSaveDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION){
            File f = dig.getSelectedFile();
        }
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        // TODO add your handling code here:
        this.lienzo.clean();
        //Lienzo2D l = new Lienzo2D();
        //lienzo = l;
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void ButtonFantasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFantasmaActionPerformed
        // TODO add your handling code here:
        this.lienzo.setTipoForma(Forma.FANTASMA);
        this.ButtonRectang.setSelected(false);
        this.ButtonCirc.setSelected(false);
        this.ButtonLinea.setSelected(false);
        this.ButtonSeleccion.setSelected(false);
        this.lienzo.setMover(false);
    }//GEN-LAST:event_ButtonFantasmaActionPerformed

    private void ButtonSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSeleccionActionPerformed
        // TODO add your handling code here:
        this.lienzo.setMover(this.ButtonSeleccion.isSelected());
        /*this.ButtonLinea.setSelected(!this.ButtonSeleccion.isSelected());
        this.ButtonRectang.setSelected(!this.ButtonSeleccion.isSelected());
        this.ButtonCirc.setSelected(!this.ButtonSeleccion.isSelected());
        this.ButtonFantasma.setSelected(!this.ButtonSeleccion.isSelected());
        this.ButtonAlisado.setSelected(!this.ButtonSeleccion.isSelected());
        this.ButtonRellenar.setSelected(!this.ButtonSeleccion.isSelected());
        this.ButtonTransparencia.setSelected(!this.ButtonSeleccion.isSelected());*/
        if (this.lienzo.getMover()){
            this.ButtonLinea.setSelected(false);
            this.ButtonRectang.setSelected(false);
            this.ButtonCirc.setSelected(false);
            this.ButtonFantasma.setSelected(false);
            this.ButtonAlisado.setSelected(false);
            this.ButtonRellenar.setSelected(false);
            this.ButtonTransparencia.setSelected(false);
        } else {
            Forma f = this.lienzo.getTipoForma();
            switch(f){
                case LINEA:
                    this.ButtonLinea.setSelected(true);
                    break;
                case RECTANGULO:
                    this.ButtonRectang.setSelected(true);
                    break;
                case ELIPSE:
                    this.ButtonCirc.setSelected(true);
                    break;
                case FANTASMA:
                    this.ButtonFantasma.setSelected(true);
                    break;
            }
            this.ButtonAlisado.setSelected(this.lienzo.getAlisado());
            this.ButtonRellenar.setSelected(this.lienzo.getRelleno());
            this.ButtonTransparencia.setSelected(this.lienzo.getTransparencia());
        }
    }//GEN-LAST:event_ButtonSeleccionActionPerformed

    private void ButtonRellenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRellenarActionPerformed
        // TODO add your handling code here:
        this.lienzo.setRelleno(this.ButtonRellenar.isSelected());
        this.ButtonSeleccion.setSelected(false);
    }//GEN-LAST:event_ButtonRellenarActionPerformed

    private void ButtonTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransparenciaActionPerformed
        // TODO add your handling code here:
        this.lienzo.setTransparencia(this.ButtonTransparencia.isSelected());
        if(this.lienzo.getTransparencia()){
            this.lienzo.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f));
        } else {
            this.lienzo.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 1));
        }
        this.ButtonSeleccion.setSelected(false);
    }//GEN-LAST:event_ButtonTransparenciaActionPerformed

    private void ButtonAlisadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlisadoActionPerformed
        // TODO add your handling code here:
        this.lienzo.setAlisado(this.ButtonAlisado.isSelected());
        this.ButtonSeleccion.setSelected(false);
    }//GEN-LAST:event_ButtonAlisadoActionPerformed

    private void SliderGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderGrosorStateChanged
        // TODO add your handling code here:
        Stroke trazo = new BasicStroke((int)SliderGrosor.getValue());
        this.lienzo.setTrazo(trazo);
        this.lienzo.repaint();
        this.ButtonSeleccion.setSelected(false);
    }//GEN-LAST:event_SliderGrosorStateChanged

    private void ButtonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonColorActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(this, "Elije un color", Color.RED);
        this.lienzo.setColor(color);
        this.ButtonColor.setBackground(color);
        this.ButtonSeleccion.setSelected(false);
    }//GEN-LAST:event_ButtonColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarraDeEstado;
    private javax.swing.JToggleButton ButtonAlisado;
    private javax.swing.JToggleButton ButtonCirc;
    private javax.swing.JButton ButtonColor;
    private javax.swing.JToggleButton ButtonFantasma;
    private javax.swing.JToggleButton ButtonLinea;
    private javax.swing.JToggleButton ButtonRectang;
    private javax.swing.JToggleButton ButtonRellenar;
    private javax.swing.JToggleButton ButtonSeleccion;
    private javax.swing.JToggleButton ButtonTransparencia;
    private javax.swing.JSlider SliderGrosor;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private sm.amc.iu.Lienzo2D lienzo;
    // End of variables declaration//GEN-END:variables

}
